onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - electron
  - esbuild
  - sharp

catalogs:
  typescript:
    typescript: 5.8.2
  drizzle:
    drizzle-kit: 0.31.0
    drizzle-orm: 0.43.1
  hookform:
    '@hookform/resolvers': 5.2.2
    react-hook-form: 7.65.0
  icons:
    lucide-react: 0.507.0
  node:
    '@types/node': ^22.18.6
  prettier:
    prettier: ^3.5.3
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-tailwindcss: ^0.6.11
  react:
    '@types/react': 19.1.3
    '@types/react-dom': 19.0.4
    react: 19.0.0
    react-dom: 19.0.0
  sqlite:
    '@types/better-sqlite3': 7.6.13
    better-sqlite3: 12.4.1
  tailwind:
    '@tailwindcss/forms': ^0.5.10
    '@tailwindcss/typography': ^0.5.16
    '@tailwindcss/vite': ^4.1.5
    tailwind-merge: ^3.2.0
    tailwindcss: ^4.1.16
  utils:
    i18next: 25.0.1
    zod: 4.1.12
    zod-i18n-map: 2.27.0
    zustand: 5.0.8
  vite:
    vite: ^7.1.12


